import Vue from 'vue';
import MaterialIcons from '@dbetka/vue-material-icons'; // sets just the max size
import es from 'vuetify/es5/locale/es';
import Vuetify, {
  VApp,
  VCard,
  VNavigationDrawer,
  VDivider,
  VMain,
  VFooter,
  VDialog,
  VListItem,
  VBtn,
  VIcon,
  VListItemContent,
  VListItemTitle,
  VListItemAvatar,
  VListItemSubtitle,
  VListItemIcon,
  VListGroup,
  VMenu,
  VSwitch,
  VBtnToggle,
  VAvatar,
  VAutocomplete,
  VSnackbar,
  VProgressLinear,
  VRow,
  VCol,
  VTooltip,
  VSkeletonLoader,
  VDataTable,
  VSelect,
  VSimpleTable,
  VContainer,
  VTextField,
  VCardTitle,
  VCardSubtitle,
  VForm,
  VTextarea,
  VCardActions,
  VCardText,
  VSpacer,
  VProgressCircular,
  VAppBar,
  VToolbarTitle,
  VAppBarNavIcon,
  VImg,
  VList,
  VListItemGroup,
  VCheckbox,
  VChip,
  VDatePicker,
  VBadge,
  VAlert,
  VTabs,
  VTab,
  VTabItem,
  VFileInput,
  VStepper,
  VStepperHeader,
  VStepperStep,
  VStepperItems,
  VStepperContent,
  VBreadcrumbs,
  VBreadcrumbsItem,
  VRadioGroup,
  VRadio,
  VSlider,
  VRangeSlider,
  VCalendar,
  VSheet,
  VExpansionPanel,
  VExpansionPanels,
  VExpansionPanelHeader,
  VExpansionPanelContent,
  VToolbar
} from 'vuetify/lib';

Vue.use(Vuetify, {
  components: {
    VApp,
    VCard,
    VNavigationDrawer,
    VDivider,
    VMain,
    VFooter,
    VDialog,
    VListItem,
    VBtn,
    VIcon,
    VListItemContent,
    VListItemTitle,
    VListItemAvatar,
    VListItemSubtitle,
    VListItemIcon,
    VListGroup,
    VMenu,
    VSwitch,
    VBtnToggle,
    VAvatar,
    VAutocomplete,
    VSnackbar,
    VProgressLinear,
    VRow,
    VCol,
    VTooltip,
    VSkeletonLoader,
    VDataTable,
    VSelect,
    VSimpleTable,
    VContainer,
    VTextField,
    VCardTitle,
    VCardSubtitle,
    VForm,
    VTextarea,
    VCardActions,
    VCardText,
    VSpacer,
    VProgressCircular,
    VAppBar,
    VToolbarTitle,
    VAppBarNavIcon,
    VImg,
    VList,
    VListItemGroup,
    VCheckbox,
    VChip,
    VDatePicker,
    VBadge,
    VAlert,
    VTabs,
    VTab,
    VTabItem,
    VFileInput,
    VStepper,
    VStepperHeader,
    VStepperStep,
    VStepperItems,
    VStepperContent,
    VBreadcrumbs,
    VBreadcrumbsItem,
    VRadioGroup,
    VRadio,
    VSlider,
    VRangeSlider,
    VCalendar,
    VSheet,
    VExpansionPanel,
    VExpansionPanels,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VToolbar
  }
});

Vue.use(MaterialIcons);

const opts = {
  options: {
    customProperties: true
  },
  icons: {
    iconfont: 'mdiSvg'
  },
  theme: {
    options: {
      customProperties: true
    },
    themes: {
      light: {
        primary: '#1b4885',
        secondary: '#006e93',
        accent: '#82B1FF',
        info: '#1680c2',
        warning: '#f9c100',
        error: '#d31419',
        success: '#449935',
        // paleta de colores
        backgroundColor: '#FFF',
        fontColor: '#303030',
        color1: '#1b4885',
        color2: '#376282',
        color3: '#5E88A9',
        color4: '#87B0D2',
        color5: '#e8fcec',
        color6: '#f3dfdf',
        ciudadania: '#1c2c84',
        linkActive: '#E5EAF2'
      },
      dark: {
        primary: '#5FC5E6',
        secondary: '#006e93',
        accent: '#82B1FF',
        info: '#88dbf7',
        warning: '#f9c100',
        error: '#d31419',
        success: '#449935',
        // paleta de colores
        backgroundColor: '#303030',
        fontColor: '#FFF',
        color1: '#5FC5E6',
        color2: '#2A9CBC',
        color3: '#007594',
        color4: '#00516D',
        color5: '#002E49',
        color6: '#5FC5E6',
        ciudadania: '#009fe3',
        linkActive: '#5b5b5b'
      }
    }
  },
  lang: {
    locales: { es },
    current: 'es'
  }
};

export default new Vuetify(opts);
